version: '2'

services:
  mailhog-secrets:
    image: twabscs/mailhog-secrets
    secrets:
    - mailhog
    environment:
      USERNAME: test
      SECRET_NAME: mailhog
    volumes:
      - appdata:/appdata
    labels:
      io.rancher.container.start_once: true
  mailhog-main:
    image: twabscs/mailhog:latest
    # environment:
    #   MH_UI_WEB_PATH: ${mh_ui_web_path}
    #   MH_SMTP_BIND_ADDR: ${mh_smtp_bind_addr}
    stdin_open: true
    tty: true
    entrypoint:
    - MailHog
    - -auth-file
    - /appdata/auth.file
    user: root
    volumes:
      - appdata:/appdata 
    labels:
      io.rancher.sidekicks: mailhog-secrets   
      io.rancher.container.pull_image: always

secrets:
  mailhog:
    external: 'true'
